### ISSUE TITLE
Error in running fpcc_test.py

### ISSUE THREAD

**Issue by lyl1140292193** [xyjbaal/fpcc_pytorch#2]
Hello, your work is so great! But I have some problems. 
When I run fpcc_test.py, the error occurred like this. By the way, instead of using fpcc-pytorch version now, I tried the tensorflow version earlier, and it's ok to run fpcc_test.py, generate txt files such as 0000_027_pred.txt successfully. But I can't train on my GPU with tf version, so I turned to learn from fpcc-pytorch version. 
I looked and compared carefully in fpcc_test.py in two versions, but still can't figured it out. I'm looking forward to your early reply~Thank you!
![314](https://user-images.githubusercontent.com/70928050/224962651-f5e83754-0100-4c15-a645-ec52d3a18f56.png)

**Comment by xyjbaal** [comment]
Thank you for your attention to our work.
The reason for this error is that the center_points found by NMS is empty.

The possible reasons are as follows:
    1. the training data and test data do not correspond, resulting in the wrong predicted center scores.
    2. center_socre_th is too large
    3. R_NMS is too large
I suggest you check the pre-processing for input data.
Hope this helps you.

**Comment by lyl1140292193** [comment]
Thank you very much! It works now!

**Comment by blandness1217** [comment]
> Thank you very much! It works now!

Hello, I met the same problem, can you tell me how you solve the problem?

**Comment by lyl1140292193** [comment]
Hello,it's because my training dataset and test dataset  do not correspond. May be you can recheck your testing procession or provide more detailed information here!
我当时是因为用于测试的和用于训练的数据不匹配，建议你检查一下测试过程中一些重要元素的值。你也可以提供更多的一些信息！

**Comment by blandness1217** [comment]
> Hello,it's because my training dataset and test dataset do not correspond. May be you can recheck your testing procession or provide more detailed information here! 我当时是因为用于测试的和用于训练的数据不匹配，建议你检查一下测试过程中一些重要元素的值。你也可以提供更多的一些信息！

Thanks for your help! I have figured out where the problem is and solved the problem.
